[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health/simple"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Force HTTPS and SSL
[deploy.https]
enabled = true
redirect = true

# Additional SSL configuration
[deploy.ssl]
enabled = true
auto = true

# Persistent volume for database files
[deploy.volumes]
data = "/app/data"

[env]
NODE_ENV = "production"
FORCE_HTTPS = "true"
RAILWAY_FORCE_HTTPS = "true"
RAILWAY_RUN_UID = "0"
RAILWAY_VOLUME_MOUNT_PATH = "/app/data"
# Railway deployment configuration for distrinaranjos
